### ISSUE TITLE
Testing viomi.vacuum.v7

### ISSUE THREAD

**Issue by igorsantos07** [nergal/homeassistant-vacuum-viomi#15]
I'm testing the integration with my v7 (the v8's Chinese version), and those are the commands I tried that work great:
- start
- pause
- stop
- set_fan_speed
- return_to_base

>Fun fact: the same `pause` command on miio2 causes the vacuum to say something after pausing, while in your case it just pauses silently.

Commands that don't work:
- locate: lol, raises NotImplementedError... but works fine on miio2
- start_pause: `AttributeError: 'MiroboVacuum2' object has no attribute 'async_start_pause'` (same for miio2)
- turn_off: doesn't seem to do anything? Didn't try further since I would probably be unable to test other services. Also doesn't do anything (nor any error logs) on miio2

I didn't try:
- turn_on: made no sense since it is on all the time and I couldn't turn it off
- send_command: no clue what it does
- clean_spot: no clue how to use it

Also, since I'm comparing working commands with miio2, an addendum: miio2 seems to update the vacuum's state (as seen via https://github.com/denysdovhan/vacuum-card) faster than this integration :thinking: 

Everything here was tried against the entity. Some commands were also tried against the device, which seems to work fine as well. Anything else I should check to say "this integration works fine with v7"? :)

**Comment by nergal** [comment]
@igorsantos07 I am appreciated for this feedback - thank you!

* locate - I wasn't able to find anything in the docs nor in the API that does this feature for my particular device, however, I can implement it "blindly" since it works for v7
* start_pause - this is the issue for sure, will be refactored
* turn_off/turn_on - needs to be retested on my end

As for the `clean_spot` - this is a part of the feature that I'm going to implement someday. It is about cleaning only a predefined part of the territory (in the same way as Xiaomi Home app does for rooms)
